// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/auth/service.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenRequest) Reset() {
	*x = GenerateTokenRequest{}
	mi := &file_api_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenRequest) ProtoMessage() {}

func (x *GenerateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenRequest.ProtoReflect.Descriptor instead.
func (*GenerateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateTokenRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GenerateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateTokenResponse) Reset() {
	*x = GenerateTokenResponse{}
	mi := &file_api_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateTokenResponse) ProtoMessage() {}

func (x *GenerateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateTokenResponse.ProtoReflect.Descriptor instead.
func (*GenerateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateTokenResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type HashPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashPasswordRequest) Reset() {
	*x = HashPasswordRequest{}
	mi := &file_api_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashPasswordRequest) ProtoMessage() {}

func (x *HashPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashPasswordRequest.ProtoReflect.Descriptor instead.
func (*HashPasswordRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *HashPasswordRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type HashPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          string                 `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HashPasswordResponse) Reset() {
	*x = HashPasswordResponse{}
	mi := &file_api_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HashPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashPasswordResponse) ProtoMessage() {}

func (x *HashPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashPasswordResponse.ProtoReflect.Descriptor instead.
func (*HashPasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *HashPasswordResponse) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type GeneratePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratePasswordResponse) Reset() {
	*x = GeneratePasswordResponse{}
	mi := &file_api_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratePasswordResponse) ProtoMessage() {}

func (x *GeneratePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratePasswordResponse.ProtoReflect.Descriptor instead.
func (*GeneratePasswordResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *GeneratePasswordResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type GetClaimsFromTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimsFromTokenRequest) Reset() {
	*x = GetClaimsFromTokenRequest{}
	mi := &file_api_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimsFromTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimsFromTokenRequest) ProtoMessage() {}

func (x *GetClaimsFromTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimsFromTokenRequest.ProtoReflect.Descriptor instead.
func (*GetClaimsFromTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_auth_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetClaimsFromTokenRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetClaimsFromTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Claims        *AuthClaims            `protobuf:"bytes,1,opt,name=claims,proto3" json:"claims,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClaimsFromTokenResponse) Reset() {
	*x = GetClaimsFromTokenResponse{}
	mi := &file_api_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClaimsFromTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClaimsFromTokenResponse) ProtoMessage() {}

func (x *GetClaimsFromTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClaimsFromTokenResponse.ProtoReflect.Descriptor instead.
func (*GetClaimsFromTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_auth_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetClaimsFromTokenResponse) GetClaims() *AuthClaims {
	if x != nil {
		return x.Claims
	}
	return nil
}

var File_api_auth_service_proto protoreflect.FileDescriptor

const file_api_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x16api/auth/service.proto\x12\x04auth\x1a\x1bgoogle/protobuf/empty.proto\x1a\x15api/auth/models.proto\"&\n" +
	"\x14GenerateTokenRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x15GenerateTokenResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"1\n" +
	"\x13HashPasswordRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"*\n" +
	"\x14HashPasswordResponse\x12\x12\n" +
	"\x04hash\x18\x01 \x01(\tR\x04hash\"6\n" +
	"\x18GeneratePasswordResponse\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\"1\n" +
	"\x19GetClaimsFromTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"H\n" +
	"\x1aGetClaimsFromTokenResponse\x12*\n" +
	"\x06claims\x18\x01 \x01(\v2\x12.models.AuthClaimsR\x06claims2\xc3\x02\n" +
	"\vAuthService\x12H\n" +
	"\rGenerateToken\x12\x1a.auth.GenerateTokenRequest\x1a\x1b.auth.GenerateTokenResponse\x12E\n" +
	"\fHashPassword\x12\x19.auth.HashPasswordRequest\x1a\x1a.auth.HashPasswordResponse\x12J\n" +
	"\x10GeneratePassword\x12\x16.google.protobuf.Empty\x1a\x1e.auth.GeneratePasswordResponse\x12W\n" +
	"\x12GetClaimsFromToken\x12\x1f.auth.GetClaimsFromTokenRequest\x1a .auth.GetClaimsFromTokenResponseB\x0fZ\rapi/auth;authb\x06proto3"

var (
	file_api_auth_service_proto_rawDescOnce sync.Once
	file_api_auth_service_proto_rawDescData []byte
)

func file_api_auth_service_proto_rawDescGZIP() []byte {
	file_api_auth_service_proto_rawDescOnce.Do(func() {
		file_api_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_auth_service_proto_rawDesc), len(file_api_auth_service_proto_rawDesc)))
	})
	return file_api_auth_service_proto_rawDescData
}

var file_api_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_api_auth_service_proto_goTypes = []any{
	(*GenerateTokenRequest)(nil),       // 0: auth.GenerateTokenRequest
	(*GenerateTokenResponse)(nil),      // 1: auth.GenerateTokenResponse
	(*HashPasswordRequest)(nil),        // 2: auth.HashPasswordRequest
	(*HashPasswordResponse)(nil),       // 3: auth.HashPasswordResponse
	(*GeneratePasswordResponse)(nil),   // 4: auth.GeneratePasswordResponse
	(*GetClaimsFromTokenRequest)(nil),  // 5: auth.GetClaimsFromTokenRequest
	(*GetClaimsFromTokenResponse)(nil), // 6: auth.GetClaimsFromTokenResponse
	(*AuthClaims)(nil),                 // 7: models.AuthClaims
	(*emptypb.Empty)(nil),              // 8: google.protobuf.Empty
}
var file_api_auth_service_proto_depIdxs = []int32{
	7, // 0: auth.GetClaimsFromTokenResponse.claims:type_name -> models.AuthClaims
	0, // 1: auth.AuthService.GenerateToken:input_type -> auth.GenerateTokenRequest
	2, // 2: auth.AuthService.HashPassword:input_type -> auth.HashPasswordRequest
	8, // 3: auth.AuthService.GeneratePassword:input_type -> google.protobuf.Empty
	5, // 4: auth.AuthService.GetClaimsFromToken:input_type -> auth.GetClaimsFromTokenRequest
	1, // 5: auth.AuthService.GenerateToken:output_type -> auth.GenerateTokenResponse
	3, // 6: auth.AuthService.HashPassword:output_type -> auth.HashPasswordResponse
	4, // 7: auth.AuthService.GeneratePassword:output_type -> auth.GeneratePasswordResponse
	6, // 8: auth.AuthService.GetClaimsFromToken:output_type -> auth.GetClaimsFromTokenResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_auth_service_proto_init() }
func file_api_auth_service_proto_init() {
	if File_api_auth_service_proto != nil {
		return
	}
	file_api_auth_models_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_auth_service_proto_rawDesc), len(file_api_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_auth_service_proto_goTypes,
		DependencyIndexes: file_api_auth_service_proto_depIdxs,
		MessageInfos:      file_api_auth_service_proto_msgTypes,
	}.Build()
	File_api_auth_service_proto = out.File
	file_api_auth_service_proto_goTypes = nil
	file_api_auth_service_proto_depIdxs = nil
}
